import type { Metadata } from "next";
import "./globals.css";
import Menu from "@/components/menu";
import { ThemeProvider } from "@/components/ThemeProvider";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.style} ${inter.style} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="flex flex-col justify-between mt-10 m-25">
          <Menu />
          {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
